export const MO_CAT = [
  { id: "mo1", cargo: "AJUDANTE", sal: 2500 },
  { id: "mo2", cargo: "MONTADOR", sal: 3400 },
  { id: "mo3", cargo: "ENCARREGADO", sal: 8600 },
  { id: "mo4", cargo: "OPERADOR DE GUINDASTE", sal: 8600 },
  { id: "mo5", cargo: "OPERADOR DE GUINCHO", sal: 4500 },
  { id: "mo6", cargo: "OPERADOR DE PULLER/FREIO", sal: 8600 },
  { id: "mo7", cargo: "OPERADOR DE TRATOR", sal: 8600 },
  { id: "mo8", cargo: "OPERADOR DE MAQUINAS", sal: 10000 },
  { id: "mo9", cargo: "MOTORISTA", sal: 3100 },
  { id: "mo10", cargo: "MOTORISTA OPERADOR MUNCK", sal: 3700 },
  { id: "mo11", cargo: "ESPOREIRO", sal: 3155 },
  { id: "mo12", cargo: "TOPOGRAFO DE OBRAS", sal: 8614 },
  { id: "mo13", cargo: "AUXILIAR DE TOPOGRAFIA", sal: 2096 },
  { id: "mo14", cargo: "NIVELADOR", sal: 3000 },
  { id: "mo15", cargo: "VIGIA", sal: 2000 },
  { id: "mo16", cargo: "MOTOSSERRISTA", sal: 3000 },
];

export const EQ_CAT = [
  { id: "eq1", nome: "GUINDASTE", loc: 150000 },
  { id: "eq2", nome: "CONJUNTO LANÇAMENTO - PULLER E FREIO", loc: 287500 },
  { id: "eq3", nome: "CAMINHÃO MUNCK", loc: 31000 },
  { id: "eq4", nome: "CAMINHÃO PRANCHA", loc: 18000 },
  { id: "eq5", nome: "CAMINHÃO CARROCERIA", loc: 18000 },
  { id: "eq6", nome: "CAMINHONETE 4X4", loc: 8500 },
  { id: "eq7", nome: "TRATOR", loc: 17000 },
  { id: "eq8", nome: "RETROESCAVADEIRA 4X4", loc: 15000 },
  { id: "eq9", nome: "GUINCHO P/ MONTAGEM", loc: 6900 },
  { id: "eq10", nome: "PRENSA HIDRAULICA P/ EMENDAS", loc: 5290 },
  { id: "eq11", nome: "MOTOSSERRA", loc: 3397.1 },
  { id: "eq12", nome: "MASTRO DE MONTAGEM", loc: 4000 },
  { id: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", loc: 9000 },
  { id: "eq14", nome: "GPS RTK", loc: 10580 },
  { id: "eq15", nome: "ESTAÇÃO TOTAL", loc: 6000 },
  { id: "eq16", nome: "MICRO ONIBUS (20 PASSAGEIROS)", loc: 16000 },
  { id: "eq17", nome: "MICRO ONIBUS (30 PASSAGEIROS)", loc: 18000 },
  { id: "eq18", nome: "ESCAVADEIRA HIDRÁULICA", loc: 25000 },
  { id: "eq19", nome: "TRATOR DE ESTEIRA", loc: 40000 },
  { id: "eq20", nome: "PÁ CARREGADEIRA", loc: 25000 },
];

export const EPC_CAT = [
  { id: "epc1", desc: "Sinalização viária", custo: 2000 },
  { id: "epc2", desc: "Corda linha de vida", custo: 1500 },
  { id: "epc3", desc: "Barreira de proteção", custo: 800 },
  { id: "epc4", desc: "Cone de sinalização (cx)", custo: 200 },
];

export const ATIVS = [
  { id: "a1", grp: "M", desc: "Pré Montagem Torre", und: "TON" },
  {
    id: "a2",
    grp: "M",
    desc: "Montagem Mecanizada",
    und: "TON",
  },
  {
    id: "a3",
    grp: "M",
    desc: "Montagem Manual",
    und: "TON",
  },
  { id: "a4", grp: "M", desc: "Revisão Torre", und: "TON" },
  { id: "a5", grp: "L", desc: "Lançamento de Cabo OPGW", und: "KM" },
  { id: "a6", grp: "L", desc: "Lançamento de Cabo Condutor", und: "KM" },
  { id: "a7", grp: "L", desc: "Grampeação de Cabo Condutor", und: "TORRE" },
];

// Composições de referência por atividade — baseadas em CBIC/ANEEL/EMOP/SINAPI.
// obrigatorio: true  → cargo/equipamento deve estar presente (qtd >= 1)
// minVarPct: -25     → coeficiente pode reduzir no máximo 25% em relação à base
// minVarPct: -100    → recurso não obrigatório, pode ser omitido
// minVarPct: null    → sem piso definido (não gera alerta de sub-alocação)
export const BASE_COMPOSITIONS = {
  a1: {
    kpi: 9,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 8,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -25,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 6,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -33,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 2,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
    ],
    eqRows: [
      {
        catId: "eq13",
        nome: "CAMINHÃO CABINADO 10 PESSOAS",
        qtd: 2,
        loc: 9000,
        horasDia: 8.5,
        obrigatorio: false,
      },
    ],
  },
  a2: {
    kpi: 36,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 10,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -20,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 5,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -20,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 2,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: null,
      },
      {
        catId: "mo4",
        cargo: "OPERADOR DE GUINDASTE",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo8",
        cargo: "OPERADOR DE MAQUINAS",
        qtd: 1,
        sal: 10000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: null,
      },
    ],
    eqRows: [
      {
        catId: "eq16",
        nome: "MICRO ONIBUS (20 PASSAGEIROS)",
        qtd: 1,
        loc: 16000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq5",
        nome: "CAMINHÃO CARROCERIA",
        qtd: 1,
        loc: 18000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq1",
        nome: "GUINDASTE",
        qtd: 1,
        loc: 150000,
        horasDia: 8.5,
        obrigatorio: true,
      },
      {
        catId: "eq20",
        nome: "PÁ CARREGADEIRA",
        qtd: 1,
        loc: 25000,
        horasDia: 8.5,
        obrigatorio: false,
      },
    ],
  },
  a3: {
    kpi: 9,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 17,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -18,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 6,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -17,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 1,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo10",
        cargo: "MOTORISTA OPERADOR MUNCK",
        qtd: 1,
        sal: 3700,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo5",
        cargo: "OPERADOR DE GUINCHO",
        qtd: 2,
        sal: 4500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -100,
      },
    ],
    eqRows: [
      {
        catId: "eq17",
        nome: "MICRO ONIBUS (30 PASSAGEIROS)",
        qtd: 1,
        loc: 18000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq3",
        nome: "CAMINHÃO MUNCK",
        qtd: 1,
        loc: 31000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq5",
        nome: "CAMINHÃO CARROCERIA",
        qtd: 1,
        loc: 18000,
        horasDia: 8.5,
        obrigatorio: true,
      },
      {
        catId: "eq9",
        nome: "GUINCHO P/ MONTAGEM",
        qtd: 2,
        loc: 6900,
        horasDia: 8.5,
        obrigatorio: true,
      },
      {
        catId: "eq12",
        nome: "MASTRO DE MONTAGEM",
        qtd: 2,
        loc: 4000,
        horasDia: 8.5,
        obrigatorio: true,
      },
    ],
  },
  a4: {
    kpi: 18,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 8,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 1,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
    ],
    eqRows: [
      {
        catId: "eq13",
        nome: "CAMINHÃO CABINADO 10 PESSOAS",
        qtd: 1,
        loc: 9000,
        horasDia: 8.5,
        obrigatorio: false,
      },
    ],
  },
  a5: {
    kpi: 1.5,
    moRows: [
      {
        catId: "mo6",
        cargo: "OPERADOR DE PULLER/FREIO",
        qtd: 2,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 8,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -22,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 5,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -22,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 2,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -50,
      },
      {
        catId: "mo10",
        cargo: "MOTORISTA OPERADOR MUNCK",
        qtd: 1,
        sal: 3700,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo15",
        cargo: "VIGIA",
        qtd: 4,
        sal: 2000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -50,
      },
    ],
    eqRows: [
      {
        catId: "eq13",
        nome: "CAMINHÃO CABINADO 10 PESSOAS",
        qtd: 2,
        loc: 9000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq3",
        nome: "CAMINHÃO MUNCK",
        qtd: 1,
        loc: 31000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq2",
        nome: "CONJUNTO LANÇAMENTO - PULLER E FREIO",
        qtd: 1,
        loc: 287500,
        horasDia: 8.5,
        obrigatorio: true,
      },
    ],
  },
  a6: {
    kpi: 1.2,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo6",
        cargo: "OPERADOR DE PULLER/FREIO",
        qtd: 2,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 12,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -17,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 8,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -25,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 4,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -50,
      },
      {
        catId: "mo10",
        cargo: "MOTORISTA OPERADOR MUNCK",
        qtd: 1,
        sal: 3700,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo8",
        cargo: "OPERADOR DE MAQUINAS",
        qtd: 1,
        sal: 10000,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo16",
        cargo: "MOTOSSERRISTA",
        qtd: 1,
        sal: 3000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -100,
      },
      {
        catId: "mo15",
        cargo: "VIGIA",
        qtd: 6,
        sal: 2000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -50,
      },
    ],
    eqRows: [
      {
        catId: "eq13",
        nome: "CAMINHÃO CABINADO 10 PESSOAS",
        qtd: 3,
        loc: 9000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq5",
        nome: "CAMINHÃO CARROCERIA",
        qtd: 1,
        loc: 18000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq3",
        nome: "CAMINHÃO MUNCK",
        qtd: 1,
        loc: 31000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq20",
        nome: "PÁ CARREGADEIRA",
        qtd: 1,
        loc: 25000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq8",
        nome: "RETROESCAVADEIRA 4X4",
        qtd: 1,
        loc: 15000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq2",
        nome: "CONJUNTO LANÇAMENTO - PULLER E FREIO",
        qtd: 1,
        loc: 287500,
        horasDia: 8.5,
        obrigatorio: true,
      },
      {
        catId: "eq11",
        nome: "MOTOSSERRA",
        qtd: 1,
        loc: 3397.1,
        horasDia: 8.5,
        obrigatorio: false,
      },
    ],
  },
  a7: {
    kpi: 3,
    moRows: [
      {
        catId: "mo3",
        cargo: "ENCARREGADO",
        qtd: 1,
        sal: 8600,
        horasDia: 8.5,
        obrigatorio: true,
        minVarPct: null,
      },
      {
        catId: "mo2",
        cargo: "MONTADOR",
        qtd: 6,
        sal: 3400,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -17,
      },
      {
        catId: "mo1",
        cargo: "AJUDANTE",
        qtd: 3,
        sal: 2500,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -33,
      },
      {
        catId: "mo9",
        cargo: "MOTORISTA",
        qtd: 2,
        sal: 3100,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -50,
      },
      {
        catId: "mo8",
        cargo: "OPERADOR DE MAQUINAS",
        qtd: 1,
        sal: 10000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -100,
      },
      {
        catId: "mo14",
        cargo: "NIVELADOR",
        qtd: 1,
        sal: 3000,
        horasDia: 8.5,
        obrigatorio: false,
        minVarPct: -100,
      },
    ],
    eqRows: [
      {
        catId: "eq13",
        nome: "CAMINHÃO CABINADO 10 PESSOAS",
        qtd: 1,
        loc: 9000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq5",
        nome: "CAMINHÃO CARROCERIA",
        qtd: 1,
        loc: 18000,
        horasDia: 8.5,
        obrigatorio: false,
      },
      {
        catId: "eq8",
        nome: "RETROESCAVADEIRA 4X4",
        qtd: 1,
        loc: 15000,
        horasDia: 8.5,
        obrigatorio: false,
      },
    ],
  },
};

// Requisitos de segurança padrão por atividade — baseados na sessão LT 500 kV CS - NORMAL AUTOPORTANTE.
// aplicavel: false  = armadilha (item que parece necessário mas NÃO se aplica à atividade)
// Total: 202 requisitos (160 aplicáveis / 42 não aplicáveis)
export const BASE_REQUIREMENTS = [
  // ─── a1: Pré Montagem Torre — 25 req (19 aplic. / 6 n.aplic.) ────
  { aId: "a1", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Detector de Tensão",                                                       aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a1", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a1", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Avental de Raspa",                                                         aplicavel: false },
  { aId: "a1", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Segurança e Saúde nos Trabalhos em Espaços Confinados",                   aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a1", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a1", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a2: Montagem Mecanizada — 31 req (24 aplic. / 7 n.aplic.) ───
  { aId: "a2", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos, equipamentos",              aplicavel: true  },
  { aId: "a2", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a2", categoria: "Projetos",      desc: "Plano de rigging",                                                         aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Içamento das estruturas excedendo a capacidade nominal do equipamento",   aplicavel: false },
  { aId: "a2", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a2", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a2", categoria: "EPIs",          desc: "Avental de Raspa",                                                         aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "Montagem Mecanizada de Estruturas Estaiadas e Autoportantes",             aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a2", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a2", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a2", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a3: Montagem Manual — 27 req (22 aplic. / 5 n.aplic.) ───────
  { aId: "a3", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a3", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Pluma com números de series divergentes entre os módulos",                aplicavel: false },
  { aId: "a3", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a3", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a3", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a3", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a3", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a3", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a3", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a4: Revisão Torre — 28 req (21 aplic. / 7 n.aplic.) ─────────
  { aId: "a4", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a4", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Pluma com números de series divergentes entre os módulos",                aplicavel: false },
  { aId: "a4", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a4", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Avental de raspa",                                                         aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a4", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a4", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a4", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a5: Lançamento de Cabo OPGW — 30 req (25 aplic. / 5 n.aplic.) ─
  { aId: "a5", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a5", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a5", categoria: "Treinamentos",  desc: "Lançamento de Cabos",                                                      aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a5", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Desligamento e/ou Bloqueio das Redes elétricas",                          aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a5", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a5", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a6: Lançamento de Cabo Condutor — 31 req (26 aplic. / 5 n.aplic.) ─
  { aId: "a6", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a6", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a6", categoria: "Treinamentos",  desc: "Instalação de Aterramentos Temporários",                                  aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Lançamento de Cabos",                                                      aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Regulagem e nivelamento de cabos",                                        aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a6", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Desligamento e/ou Bloqueio das Redes elétricas",                          aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a6", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },

  // ─── a7: Grampeação de Cabo Condutor — 30 req (23 aplic. / 7 n.aplic.) ─
  { aId: "a7", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a7", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a7", categoria: "Treinamentos",  desc: "Instalação de Aterramentos Temporários",                                  aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a7", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a7", categoria: "EPIs",          desc: "Avental de raspa",                                                         aplicavel: false },
  { aId: "a7", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a7", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
];
export const REQ_CATEGORIAS = [
  "Procedimento",
  "EPC",
  "EPIs",
  "Treinamentos",
  "Projetos",
  "Outros",
];
export const REQ_TEMPOS = [0, 15, 30, 45, 60, 90, 120];
export const REQ_CAT_COLORS = {
  Procedimento: "#6366F1",
  EPC: "#F59E0B",
  EPIs: "#10B981",
  Treinamentos: "#EC4899",
  Projetos: "#8B5CF6",
  Outros: "#9CA3AF",
};
