import { MoCatItem, EqCatItem, InsumoCatItem, EpcCatItem, AtividadeItem } from "../types";

export const MO_CAT: MoCatItem[] = [
  { id: "mo1", cargo: { pt: "AJUDANTE", es: "AYUDANTE" }, sal: 2500 },
  { id: "mo2", cargo: { pt: "MONTADOR", es: "MONTADOR" }, sal: 3400 },
  { id: "mo3", cargo: { pt: "ENCARREGADO", es: "ENCARGADO" }, sal: 8600 },
  { id: "mo4", cargo: { pt: "OPERADOR DE GUINDASTE", es: "OPERADOR DE GRÚA" }, sal: 8600 },
  { id: "mo5", cargo: { pt: "OPERADOR DE GUINCHO", es: "OPERADOR DE CABRESTANTE" }, sal: 4500 },
  { id: "mo6", cargo: { pt: "OPERADOR DE PULLER/FREIO", es: "OPERADOR DE PULLER/FRENO" }, sal: 8600 },
  { id: "mo7", cargo: { pt: "OPERADOR DE TRATOR", es: "OPERADOR DE TRACTOR" }, sal: 8600 },
  { id: "mo8", cargo: { pt: "OPERADOR DE MAQUINAS", es: "OPERADOR DE MAQUINARIA" }, sal: 10000 },
  { id: "mo9", cargo: { pt: "MOTORISTA", es: "CONDUCTOR" }, sal: 3100 },
  { id: "mo10", cargo: { pt: "MOTORISTA OPERADOR MUNCK", es: "CONDUCTOR OPERADOR DE CAMIÓN PLUMA" }, sal: 3700 },
  { id: "mo11", cargo: { pt: "ESPOREIRO", es: "LINIERO TREPADOR" }, sal: 3155 },
  { id: "mo12", cargo: { pt: "TOPOGRAFO DE OBRAS", es: "TOPÓGRAFO DE OBRAS" }, sal: 8614 },
  { id: "mo13", cargo: { pt: "AUXILIAR DE TOPOGRAFIA", es: "AUXILIAR DE TOPOGRAFÍA" }, sal: 2096 },
  { id: "mo14", cargo: { pt: "NIVELADOR", es: "NIVELADOR" }, sal: 3000 },
  { id: "mo15", cargo: { pt: "VIGIA", es: "VIGÍA" }, sal: 2000 },
  { id: "mo16", cargo: { pt: "MOTOSSERRISTA", es: "MOTOSERRISTA" }, sal: 3000 },
];

export const EQ_CAT: EqCatItem[] = [
  { id: "eq1", nome: { pt: "GUINDASTE", es: "GRÚA" }, loc: 150000 },
  { id: "eq2", nome: { pt: "CONJUNTO LANÇAMENTO - PULLER E FREIO", es: "CONJUNTO DE TENDIDO - PULLER Y FRENO" }, loc: 287500 },
  { id: "eq3", nome: { pt: "CAMINHÃO MUNCK", es: "CAMIÓN PLUMA" }, loc: 31000 },
  { id: "eq4", nome: { pt: "CAMINHÃO PRANCHA", es: "CAMIÓN GÓNDOLA / PLATAFORMA" }, loc: 18000 },
  { id: "eq5", nome: { pt: "CAMINHÃO CARROCERIA", es: "CAMIÓN CARROCERÍA" }, loc: 18000 },
  { id: "eq6", nome: { pt: "CAMINHONETE 4X4", es: "CAMIONETA 4X4" }, loc: 8500 },
  { id: "eq7", nome: { pt: "TRATOR", es: "TRACTOR" }, loc: 17000 },
  { id: "eq8", nome: { pt: "RETROESCAVADEIRA 4X4", es: "RETROEXCAVADORA 4X4" }, loc: 15000 },
  { id: "eq9", nome: { pt: "GUINCHO P/ MONTAGEM", es: "CABRESTANTE DE MONTAJE" }, loc: 6900 },
  { id: "eq10", nome: { pt: "PRENSA HIDRAULICA P/ EMENDAS", es: "PRENSA HIDRÁULICA PARA EMPALMES" }, loc: 5290 },
  { id: "eq11", nome: { pt: "MOTOSSERRA", es: "MOTOSIERRA" }, loc: 3397.1 },
  { id: "eq12", nome: { pt: "MASTRO DE MONTAGEM", es: "MÁSTIL DE MONTAJE" }, loc: 4000 },
  { id: "eq13", nome: { pt: "CAMINHÃO CABINADO 10 PESSOAS", es: "CAMIÓN CABINADO PARA PERSONAL" }, loc: 9000 },
  { id: "eq14", nome: { pt: "GPS RTK", es: "GPS RTK" }, loc: 10580 },
  { id: "eq15", nome: { pt: "ESTAÇÃO TOTAL", es: "ESTACIÓN TOTAL" }, loc: 6000 },
  { id: "eq16", nome: { pt: "MICRO ONIBUS (20 PASSAGEIROS)", es: "MICROBÚS (20 PASAJEROS)" }, loc: 16000 },
  { id: "eq17", nome: { pt: "MICRO ONIBUS (30 PASSAGEIROS)", es: "MICROBÚS (30 PASAJEROS)" }, loc: 18000 },
  { id: "eq18", nome: { pt: "ESCAVADEIRA HIDRÁULICA", es: "EXCAVADORA HIDRÁULICA" }, loc: 25000 },
  { id: "eq19", nome: { pt: "TRATOR DE ESTEIRA", es: "TRACTOR DE ORUGAS" }, loc: 40000 },
  { id: "eq20", nome: { pt: "PÁ CARREGADEIRA", es: "PALA CARGADORA" }, loc: 25000 },
];

// Ferramental/Insumo — custo único (fixo). Catálogo padrão (sobrescrito por evento).
export const INSUMO_CAT: InsumoCatItem[] = [
  { id: "ins1", nome: { pt: "CABO CONDUTOR (BOBINA)", es: "CABLE CONDUCTOR (BOBINA)" }, custo: 50000 },
  { id: "ins2", nome: { pt: "CABO OPGW (BOBINA)", es: "CABLE OPGW (BOBINA)" }, custo: 35000 },
  { id: "ins3", nome: { pt: "CADEIA DE ISOLADORES", es: "CADENA DE AISLADORES" }, custo: 1800 },
  { id: "ins4", nome: { pt: "GRAMPO DE ANCORAGEM", es: "GRAPA DE ANCLAJE" }, custo: 450 },
  { id: "ins5", nome: { pt: "EMENDA PREFORMADA", es: "EMPALME PREFORMADO" }, custo: 900 },
];

export const EPC_CAT: EpcCatItem[] = [
  { id: "epc1", desc: { pt: "Sinalização viária", es: "Señalización vial" }, custo: 2000 },
  { id: "epc2", desc: { pt: "Corda linha de vida", es: "Cuerda línea de vida" }, custo: 1500 },
  { id: "epc3", desc: { pt: "Barreira de proteção", es: "Barrera de protección" }, custo: 800 },
  { id: "epc4", desc: { pt: "Cone de sinalização (cx)", es: "Cono de señalización (caja)" }, custo: 200 },
];

export const ATIVS: AtividadeItem[] = [
  { id: "a1", grp: "M", desc: { pt: "Pré Montagem Torre", es: "Premontaje de Torre" }, und: { pt: "TON", es: "TON" } },
  { id: "a2", grp: "M", desc: { pt: "Montagem Mecanizada", es: "Montaje Mecanizado" }, und: { pt: "TON", es: "TON" } },
  { id: "a3", grp: "M", desc: { pt: "Montagem Manual", es: "Montaje Manual" }, und: { pt: "TON", es: "TON" } },
  { id: "a4", grp: "M", desc: { pt: "Revisão Torre", es: "Revisión de Torre" }, und: { pt: "TON", es: "TON" } },
  { id: "a5", grp: "L", desc: { pt: "Lançamento de Cabo OPGW", es: "Tendido de Cable OPGW" }, und: { pt: "KM", es: "KM" } },
  { id: "a6", grp: "L", desc: { pt: "Lançamento de Cabo Condutor", es: "Tendido de Cable Conductor" }, und: { pt: "KM", es: "KM" } },
  { id: "a7", grp: "L", desc: { pt: "Grampeação de Cabo Condutor", es: "Engrapado de Cable Conductor" }, und: { pt: "TORRE", es: "TORRE" } },
];

// Mapeamento de traduções de Requisitos de Segurança Padrão (pt -> es)
export const REQ_TRANSLATIONS: Record<string, string> = {
  "Procedimento Específico da atividade": "Procedimiento Específico de la actividad",
  "Análise Preliminar de Riscos (APR)": "Análisis Preliminar de Riesgos (APR)",
  "Planilha de Perigos e Riscos (PPR)": "Planilla de Peligros y Riesgos (PPR)",
  "Permissão de Trabalho Específico (PTE)": "Permiso de Trabajo Específico (PTE)",
  "Diálogo Diário de Segurança (DDS)": "Diálogo Diario de Seguridad (DDS)",
  "Detector de Tensão": "Detector de Tensión",
  "Plano de Atendimento de Emergências (PAE)": "Plan de Atención de Emergencias (PAE)",
  "Checklist específico para máquinas, veículos e equipamentos": "Checklist específico para máquinas, vehículos y equipos",
  "Especificações técnicas e projetos": "Especificaciones técnicas y proyectos",
  "Relatórios de inspeção de acessórios e equipamentos (Laudos)": "Informes de inspección de accesorios y equipos (Laudos)",
  "Protocolo da atividade / Duplo Check": "Protocolo de la actividad / Doble Check",
  "Capacete": "Casco",
  "Óculos": "Gafas de seguridad",
  "Botina": "Botas de seguridad",
  "Uniforme Padrão": "Uniforme Estándar",
  "Botina de segurança com biqueira de aço": "Botas de seguridad con puntera de acero",
  "Luvas de segurança": "Guantes de seguridad",
  "Avental de Raspa": "Delantal de cuero/raspa",
  "Máscara de solda": "Máscara de soldadura",
  "Integração de Saúde e Segurança": "Inducción de Salud y Seguridad",
  "Segurança e Saúde nos Trabalhos em Espaços Confinados": "Seguridad y Salud en Trabajos en Espacios Confinados",
  "Movimentação de Produtos Perigosos - MOPP": "Transporte de Mercancías Peligrosas",
  "Sinalização": "Señalización",
  "Autofalante": "Megáfono / Altavoz",
  "Perneira de proteção": "Polainas de protección",
  "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda": "Arnés de Seguridad tipo paracaidista y dispositivos anticaídas",
  "NR 18 - Integração de Saúde e Segurança": "NR 18 - Inducción de Salud y Seguridad",
  "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados": "NR-33 - Seguridad y Salud en Trabajos en Espacios Confinados",
  "NR-35 - Trabalho em Altura": "NR-35 - Trabajo en Altura",
  "Montagem Mecanizada de Estruturas Estaiadas e Autoportantes": "Montaje Mecanizado de Estructuras Atirantadas y Autoportantes",
  "Utilização e Inspeção em Acessórios de Carga": "Uso e Inspección de Accesorios de Carga",
  "Corda Linha de vida": "Cuerda Línea de vida",
  "Pluma com números de series divergentes entre os módulos": "Pluma con números de series divergentes entre los módulos",
  "NR-10 – Básico / SEP": "NR-10 – Básico / SEP",
  "Segurança em Atividades com corte e solda": "Seguridad en Actividades con corte y soldadura",
  "Lançamento de Cabos": "Tendido de Cables",
  "Desligamento e/ou Bloqueio das Redes elétricas": "Desconexión y/o Bloqueo de Redes eléctricas",
  "5 Regras de Ouro": "5 Reglas de Oro",
  "Aterramento Temporário": "Puesta a Tierra Temporal",
  "Ponte para atravessar de uma fase para outra": "Puente para cruzar de una fase a otra",
  "Instalação de Aterramentos Temporários": "Instalación de Puestas a Tierra Temporales",
  "Regulagem e nivelamento de cabos": "Regulación y nivelación de cables",
  "Uniforme Antichama": "Uniforme Ignífugo / Antichama",
  "Especificações técnicas, projetos, planos de lançamentos": "Especificaciones técnicas, proyectos, planes de tendido",
  "Avental de raspa": "Delantal de cuero/raspa",
  "Plano de rigging": "Plan de izaje (rigging)",
  "Içamento das estruturas excedendo a capacidade nominal do equipamento": "Izaje de estructuras excediendo la capacidad nominal del equipo",
};

// Mapeamento de Categorias de Requisitos (pt -> es)
export const CAT_TRANSLATIONS: Record<string, string> = {
  "Procedimento": "Procedimiento",
  "EPC": "EPC",
  "EPIs": "EPIs",
  "Treinamentos": "Capacitación",
  "Projetos": "Proyectos",
  "Outros": "Otros",
};

export const BASE_COMPOSITIONS = {
  a1: {
    kpi: 9,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 8, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -25 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 6, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -33 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 2, sal: 3100, horasDia: 8.5, obrigatorio: true, minVarPct: null },
    ],
    eqRows: [
      { catId: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", qtd: 2, loc: 9000, horasDia: 8.5, obrigatorio: false },
    ],
  },
  a2: {
    kpi: 36,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 10, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -20 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 5, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -20 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 2, sal: 3100, horasDia: 8.5, obrigatorio: false, minVarPct: null },
      { catId: "mo4", cargo: "OPERADOR DE GUINDASTE", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo8", cargo: "OPERADOR DE MAQUINAS", qtd: 1, sal: 10000, horasDia: 8.5, obrigatorio: false, minVarPct: null },
    ],
    eqRows: [
      { catId: "eq16", nome: "MICRO ONIBUS (20 PASSAGEIROS)", qtd: 1, loc: 16000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq5", nome: "CAMINHÃO CARROCERIA", qtd: 1, loc: 18000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq1", nome: "GUINDASTE", qtd: 1, loc: 150000, horasDia: 8.5, obrigatorio: true },
      { catId: "eq20", nome: "PÁ CARREGADEIRA", qtd: 1, loc: 25000, horasDia: 8.5, obrigatorio: false },
    ],
  },
  a3: {
    kpi: 9,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 17, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -18 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 6, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -17 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 1, sal: 3100, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo10", cargo: "MOTORISTA OPERADOR MUNCK", qtd: 1, sal: 3700, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo5", cargo: "OPERADOR DE GUINCHO", qtd: 2, sal: 4500, horasDia: 8.5, obrigatorio: false, minVarPct: -100 },
    ],
    eqRows: [
      { catId: "eq17", nome: "MICRO ONIBUS (30 PASSAGEIROS)", qtd: 1, loc: 18000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq3", nome: "CAMINHÃO MUNCK", qtd: 1, loc: 31000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq5", nome: "CAMINHÃO CARROCERIA", qtd: 1, loc: 18000, horasDia: 8.5, obrigatorio: true },
      { catId: "eq9", nome: "GUINCHO P/ MONTAGEM", qtd: 2, loc: 6900, horasDia: 8.5, obrigatorio: true },
      { catId: "eq12", nome: "MASTRO DE MONTAGEM", qtd: 2, loc: 4000, horasDia: 8.5, obrigatorio: true },
    ],
  },
  a4: {
    kpi: 18,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 8, sal: 3400, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 1, sal: 3100, horasDia: 8.5, obrigatorio: true, minVarPct: null },
    ],
    eqRows: [
      { catId: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", qtd: 1, loc: 9000, horasDia: 8.5, obrigatorio: false },
    ],
  },
  a5: {
    kpi: 1.5,
    moRows: [
      { catId: "mo6", cargo: "OPERADOR DE PULLER/FREIO", qtd: 2, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 8, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -22 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 5, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -22 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 2, sal: 3100, horasDia: 8.5, obrigatorio: false, minVarPct: -50 },
      { catId: "mo10", cargo: "MOTORISTA OPERADOR MUNCK", qtd: 1, sal: 3700, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo15", cargo: "VIGIA", qtd: 4, sal: 2000, horasDia: 8.5, obrigatorio: false, minVarPct: -50 },
    ],
    eqRows: [
      { catId: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", qtd: 2, loc: 9000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq3", nome: "CAMINHÃO MUNCK", qtd: 1, loc: 31000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq2", nome: "CONJUNTO LANÇAMENTO - PULLER E FREIO", qtd: 1, loc: 287500, horasDia: 8.5, obrigatorio: true },
    ],
  },
  a6: {
    kpi: 1.2,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo6", cargo: "OPERADOR DE PULLER/FREIO", qtd: 2, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 12, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -17 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 8, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -25 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 4, sal: 3100, horasDia: 8.5, obrigatorio: false, minVarPct: -50 },
      { catId: "mo10", cargo: "MOTORISTA OPERADOR MUNCK", qtd: 1, sal: 3700, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo8", cargo: "OPERADOR DE MAQUINAS", qtd: 1, sal: 10000, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo16", cargo: "MOTOSSERRISTA", qtd: 1, sal: 3000, horasDia: 8.5, obrigatorio: false, minVarPct: -100 },
      { catId: "mo15", cargo: "VIGIA", qtd: 6, sal: 2000, horasDia: 8.5, obrigatorio: false, minVarPct: -50 },
    ],
    eqRows: [
      { catId: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", qtd: 3, loc: 9000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq5", nome: "CAMINHÃO CARROCERIA", qtd: 1, loc: 18000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq3", nome: "CAMINHÃO MUNCK", qtd: 1, loc: 31000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq20", nome: "PÁ CARREGADEIRA", qtd: 1, loc: 25000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq8", nome: "RETROESCAVADEIRA 4X4", qtd: 1, loc: 15000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq2", nome: "CONJUNTO LANÇAMENTO - PULLER E FREIO", qtd: 1, loc: 287500, horasDia: 8.5, obrigatorio: true },
      { catId: "eq11", nome: "MOTOSSERRA", qtd: 1, loc: 3397.1, horasDia: 8.5, obrigatorio: false },
    ],
  },
  a7: {
    kpi: 3,
    moRows: [
      { catId: "mo3", cargo: "ENCARREGADO", qtd: 1, sal: 8600, horasDia: 8.5, obrigatorio: true, minVarPct: null },
      { catId: "mo2", cargo: "MONTADOR", qtd: 6, sal: 3400, horasDia: 8.5, obrigatorio: false, minVarPct: -17 },
      { catId: "mo1", cargo: "AJUDANTE", qtd: 3, sal: 2500, horasDia: 8.5, obrigatorio: false, minVarPct: -33 },
      { catId: "mo9", cargo: "MOTORISTA", qtd: 2, sal: 3100, horasDia: 8.5, obrigatorio: false, minVarPct: -50 },
      { catId: "mo8", cargo: "OPERADOR DE MAQUINAS", qtd: 1, sal: 10000, horasDia: 8.5, obrigatorio: false, minVarPct: -100 },
      { catId: "mo14", cargo: "NIVELADOR", qtd: 1, sal: 3000, horasDia: 8.5, obrigatorio: false, minVarPct: -100 },
    ],
    eqRows: [
      { catId: "eq13", nome: "CAMINHÃO CABINADO 10 PESSOAS", qtd: 1, loc: 9000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq5", nome: "CAMINHÃO CARROCERIA", qtd: 1, loc: 18000, horasDia: 8.5, obrigatorio: false },
      { catId: "eq8", nome: "RETROESCAVADEIRA 4X4", qtd: 1, loc: 15000, horasDia: 8.5, obrigatorio: false },
    ],
  },
};

export const BASE_REQUIREMENTS = [
  // ─── a1: Pré Montagem Torre ────
  { aId: "a1", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Detector de Tensão",                                                       aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a1", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a1", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a1", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Avental de Raspa",                                                         aplicavel: false },
  { aId: "a1", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a1", categoria: "Treinamentos",  desc: "Segurança e Saúde nos Trabalhos em Espaços Confinados",                   aplicavel: false },
  { aId: "a1", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a1", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a1", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: true  },
  { aId: "a1", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a2: Montagem Mecanizada ───
  { aId: "a2", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos, equipamentos",              aplicavel: true  },
  { aId: "a2", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a2", categoria: "Projetos",      desc: "Plano de rigging",                                                         aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Içamento das estruturas excedendo a capacidade nominal do equipamento",   aplicavel: false },
  { aId: "a2", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a2", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a2", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a2", categoria: "EPIs",          desc: "Avental de Raspa",                                                         aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a2", categoria: "Treinamentos",  desc: "Montagem Mecanizada de Estruturas Estaiadas e Autoportantes",             aplicavel: true  },
  { aId: "a2", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a2", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a2", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a2", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a2", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a3: Montagem Manual ───────
  { aId: "a3", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a3", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Pluma com números de series divergentes entre os módulos",                aplicavel: false },
  { aId: "a3", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a3", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a3", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a3", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a3", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a3", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a3", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a3", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a3", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a3", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a4: Revisão Torre ─────────
  { aId: "a4", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a4", categoria: "Projetos",      desc: "Especificações técnicas e projetos",                                       aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Pluma com números de series divergentes entre os módulos",                aplicavel: false },
  { aId: "a4", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a4", categoria: "Procedimento",  desc: "Protocolo da atividade / Duplo Check",                                     aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Integração de Saúde e Segurança",                                          aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a4", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a4", categoria: "Treinamentos",  desc: "Movimentação de Produtos Perigosos - MOPP",                               aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Uniforme Padrão",                                                          aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Avental de raspa",                                                         aplicavel: false },
  { aId: "a4", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a4", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a4", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a4", categoria: "EPC",           desc: "Corda Linha de vida",                                                      aplicavel: true  },
  { aId: "a4", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a5: Lançamento de Cabo OPGW ─
  { aId: "a5", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a5", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a5", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a5", categoria: "Treinamentos",  desc: "Lançamento de Cabos",                                                      aplicavel: true  },
  { aId: "a5", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a5", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a5", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Desligamento e/ou Bloqueio das Redes elétricas",                          aplicavel: true  },
  { aId: "a5", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a5", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a5", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
  { aId: "a5", categoria: "EPIs",          desc: "Perneira de proteção",                                                     aplicavel: true  },

  // ─── a6: Lançamento de Cabo Condutor ─
  { aId: "a6", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a6", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a6", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a6", categoria: "Treinamentos",  desc: "Instalação de Aterramentos Temporários",                                  aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Lançamento de Cabos",                                                      aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a6", categoria: "Treinamentos",  desc: "Regulagem e nivelamento de cabos",                                        aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a6", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a6", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Desligamento e/ou Bloqueio das Redes elétricas",                          aplicavel: true  },
  { aId: "a6", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a6", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a6", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },

  // ─── a7: Grampeação de Cabo Condutor ─
  { aId: "a7", categoria: "Procedimento",  desc: "Procedimento Específico da atividade",                                     aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Análise Preliminar de Riscos (APR)",                                       aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Planilha de Perigos e Riscos (PPR)",                                       aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Permissão de Trabalho Específico (PTE)",                                   aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Diálogo Diário de Segurança (DDS)",                                        aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Plano de Atendimento de Emergências (PAE)",                                aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Checklist específico para máquinas, veículos e equipamentos",              aplicavel: true  },
  { aId: "a7", categoria: "Projetos",      desc: "Especificações técnicas, projetos, planos de lançamentos",                 aplicavel: true  },
  { aId: "a7", categoria: "Procedimento",  desc: "Relatórios de inspeção de acessórios e equipamentos (Laudos)",             aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR 18 - Integração de Saúde e Segurança",                                  aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-10 – Básico / SEP",                                                    aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-33 - Segurança e Saúde nos Trabalhos em Espaços Confinados",           aplicavel: false },
  { aId: "a7", categoria: "Treinamentos",  desc: "NR-35 - Trabalho em Altura",                                              aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Segurança em Atividades com corte e solda",                               aplicavel: false },
  { aId: "a7", categoria: "Treinamentos",  desc: "Instalação de Aterramentos Temporários",                                  aplicavel: true  },
  { aId: "a7", categoria: "Treinamentos",  desc: "Utilização e Inspeção em Acessórios de Carga",                            aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Capacete",                                                                 aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Óculos",                                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Botina",                                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Uniforme Antichama",                                                       aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Cinto de Segurança tipo paraquedista e dispositivos retenção de queda",   aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Botina de segurança com biqueira de aço",                                  aplicavel: false },
  { aId: "a7", categoria: "EPIs",          desc: "Luvas de segurança",                                                       aplicavel: true  },
  { aId: "a7", categoria: "EPIs",          desc: "Máscara de solda",                                                         aplicavel: false },
  { aId: "a7", categoria: "EPIs",          desc: "Avental de raspa",                                                         aplicavel: false },
  { aId: "a7", categoria: "Procedimento",  desc: "5 Regras de Ouro",                                                         aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Aterramento Temporário",                                                   aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Ponte para atravessar de uma fase para outra",                            aplicavel: false },
  { aId: "a7", categoria: "EPC",           desc: "Sinalização",                                                              aplicavel: true  },
  { aId: "a7", categoria: "EPC",           desc: "Autofalante",                                                              aplicavel: false },
];

export const REQ_CATEGORIAS = [
  "Procedimento",
  "EPC",
  "EPIs",
  "Treinamentos",
  "Projetos",
  "Outros",
];

export const REQ_TEMPOS = [0, 15, 30, 45, 60, 90, 120];

export const REQ_CAT_COLORS = {
  Procedimento: "#6366F1",
  EPC: "#F59E0B",
  EPIs: "#10B981",
  Treinamentos: "#EC4899",
  Projetos: "#8B5CF6",
  Outros: "#9CA3AF",
};
